'use strict';
const crypto=require('crypto');
const DB=require('../lib/db'),U=require('../lib/utils'),V=require('./views');
const MODEL=require('../lib/programme-modele.json');
const GROUPS=[
 ['Identité et diplôme',[['titre','Intitulé du programme'],['code','Code du programme'],['institution','Établissement délivrant'],['departement','Département'],['version','Version du document'],['anneeAcademique','Année académique / cohorte'],['diplome','Intitulé exact du diplôme'],['grade','Grade / qualification'],['niveauSortie','Niveau de sortie'],['dureeAnnees','Durée en années','number'],['semestres','Nombre de semestres','number'],['heuresAnnoncees','Volume global annoncé (heures)','number'],['langue','Langue d’enseignement'],['modalite','Modalité et lieu'],['responsable','Responsable pédagogique'],['contact','Contact'],['frais','Frais et modalités de paiement'],['partenaires','Partenaires','area'],['reconnaissance','Reconnaissance / habilitation documentée','area'],['informationsComplementaires','Informations complémentaires du document source','area']]],
 ['Présentation et admission',[['presentation','Présentation complète','area'],['publicCible','Public cible','area'],['admission','Conditions d’admission','area'],['objectifs','Objectifs généraux','area'],['competences','Compétences de sortie','area'],['debouches','Débouchés et poursuite d’études','area'],['methodes','Méthodes pédagogiques','area'],['materiels','Équipements, logiciels et ressources','area']]],
 ['Organisation et volume horaire',[['organisation','Années, semestres, intitulés et progression','area'],['volumeGlobal','Répartition globale par année et composante','area'],['projets','Projets intégrateurs par semestre et livrables','area']]],
 ['Stage et projet final',[['stageSemaines','Durée du stage (semaines)','number'],['stageHeures','Volume du stage (heures)','number'],['stageDetails','Stage : organisme, tutorat, journal, rapport et soutenance','area'],['pffDetails','Projet final : livrables, suivi, jury et présentation','area']]],
 ['Évaluations et diplomation',[['libelleControle','Intitulé de la première composante'],['poidsControle','Première composante (%)','number'],['libelleProjets','Intitulé de la deuxième composante'],['poidsProjets','Deuxième composante (%)','number'],['libelleComplementaire','Intitulé de la composante complémentaire'],['poidsComplementaire','Composante complémentaire (%)','number'],['libelleStage','Intitulé de la composante finale'],['poidsStage','Composante finale (%)','number'],['seuilComposante','Seuil minimal par composante (/100)','number'],['seuilPFF','Seuil du projet final (/100)','number'],['absenceMax','Absences non justifiées maximales (%)','number'],['evaluationDetails','Épreuves, critères et modalités d’évaluation','area'],['conditionsDiplome','Conditions complètes d’obtention du diplôme','area']]]
];
const FIELDS=GROUPS.flatMap(g=>g[1]);
const esc=U.esc;
const html=(t,c,user)=>V.layout(t,`<div class="page-head"><span class="eyebrow">PROGRAMMES LONGS</span><h1>${esc(t)}</h1></div>${c}`,{user,active:'/programmes'});
const blocks=t=>`<p style="white-space:pre-wrap">${esc(t||'À préciser')}</p>`;
const csrf=u=>{if(!u.programmeCsrf){u.programmeCsrf=crypto.randomBytes(24).toString('hex');DB.save();}return u.programmeCsrf;};
const access=(u,p)=>!!u&&(u.role==='admin'||u.role==='formateur'&&p.ownerId===u.id);
const canWrite=u=>u&&(u.role==='admin'||u.role==='formateur'&&(!u.candidature||u.candidature.statut==='approuvee'));
const total=p=>(p.modules||[]).reduce((s,m)=>s+(+m.theorie||0)+(+m.pratique||0)+(+m.stage||0),0);
function editor(p,user,error=''){
 const field=([k,label,type])=>`<div><label for="pg-${k}">${esc(label)}</label>${type==='area'?`<textarea id="pg-${k}" name="${k}" rows="4" maxlength="12000">${esc(p[k]||'')}</textarea>`:`<input id="pg-${k}" name="${k}" type="${type==='number'?'number':'text'}" ${type==='number'?'min="0" step="1"':'maxlength="1000"'} ${['titre','diplome'].includes(k)?'required':''} value="${esc(p[k]??'')}">`}</div>`;
 return html(p.id?'Configurer le programme':'Créer un programme long',`<p><a href="/formateur/programmes">← Mes programmes</a></p>${error?`<div role="alert" class="alerte ko">${esc(error)}</div>`:''}
 <form id="programme-form" method="POST" action="/formateur/programmes/${p.id||'nouveau'}"><input type="hidden" name="csrf" value="${csrf(user)}">
 ${GROUPS.map(([name,fields])=>`<details class="carte" open style="margin-bottom:16px"><summary><b>${name}</b></summary><div class="grille g2" style="margin-top:14px">${fields.map(field).join('')}</div></details>`).join('')}
 <section class="carte"><h2>Modules du programme</h2><p>Organisez les modules par année et semestre. Ajoutez leur contenu, leurs objectifs spécifiques, leurs heures, crédits et évaluations.</p><p id="volume-info" class="panneau"></p><div id="modules-editor"></div><button type="button" class="btn ligne" id="add-module">+ Ajouter un module</button><input type="hidden" name="modules" id="modules-value"></section>
 <section class="carte" style="margin-top:16px"><label>État de publication</label><select name="statut"><option value="brouillon" ${p.statut!=='publie'?'selected':''}>Brouillon privé</option><option value="publie" ${p.statut==='publie'?'selected':''}>Publié dans les programmes longs</option></select><label style="margin-top:12px"><input type="checkbox" name="confirmerHeures" value="oui" style="width:auto" ${p.confirmerHeures?'checked':''}> J’ai vérifié les différences entre le volume annoncé et les modules détaillés (projets / suivi sans volume chiffré, etc.).</label><button class="btn" style="margin-top:16px">Enregistrer le programme</button></section></form>
 <script type="application/json" id="program-data">${JSON.stringify(p.modules||[]).replace(/</g,'\\u003c')}</script><script src="/assets/programmes.js" defer></script>`,user);
}
function details(p,user,print=false){
 const stats=`<div class="grille g4">${[[p.grade,p.diplome],[p.dureeAnnees+' ans',p.semestres+' semestres'],[p.heuresAnnoncees+' h','Volume annoncé'],[p.langue,p.modalite]].map(([v,l])=>`<div class="carte stat-carte"><span class="val" style="font-size:20px">${esc(v)}</span><span class="lib">${esc(l||'')}</span></div>`).join('')}</div>`;
 const mods=[...p.modules].sort((a,b)=>a.annee-b.annee||a.semestre-b.semestre);
 let previous='';const curriculum=mods.map(m=>{const group=`Année ${m.annee} · Semestre ${m.semestre}`;const head=group!==previous?`<h2>${group}</h2>`:'';previous=group;return `${head}<article class="carte" style="margin-bottom:12px;break-inside:avoid"><h3>${esc(m.code)} — ${esc(m.titre)}</h3>${blocks(m.contenu)}<p><b>Volume :</b> ${m.theorie} h théorie · ${m.pratique} h pratique · ${m.stage} h stage${m.credits?' · '+m.credits+' crédits':''}</p>${m.notesHoraires?blocks(m.notesHoraires):''}${m.prerequis?'<b>Prérequis</b>'+blocks(m.prerequis):''}${m.objectifs?'<b>Objectifs spécifiques</b>'+blocks(m.objectifs):''}${m.evaluation?'<b>Évaluation</b>'+blocks(m.evaluation):''}</article>`;}).join('');
 const parts=GROUPS.map(([title,fields])=>`<section class="carte" style="margin-top:16px"><h2>${title}</h2>${fields.filter(([k])=>p[k]!==''&&p[k]!==undefined).map(([k,label])=>`<h3 style="font-size:15px">${esc(label)}</h3>${blocks(p[k])}`).join('')}</section>`).join('');
 return html(p.titre,`<div class="actions-h" style="margin-bottom:16px"><a class="btn ligne" href="/programmes">Tous les programmes</a>${access(user,p)?`<a class="btn" href="/formateur/programmes/${p.id}">Configurer</a>`:''}${p.source?`<a class="btn ligne" href="/programmes/${p.id}/source">Document PDF source</a>`:''}<button class="btn ligne" onclick="window.print()">Imprimer / enregistrer en PDF</button></div>${stats}${p.statut!=='publie'?'<p class="alerte ko">Brouillon privé — non publié</p>':''}${parts}<section><h2>Parcours détaillé</h2>${curriculum}</section><p class="panneau">Total chiffré des modules : ${total(p)} h. Volume global annoncé : ${p.heuresAnnoncees} h.${total(p)!==p.heuresAnnoncees?' La répartition comporte une différence ; consultez les notes horaires et la répartition globale.':''}</p><style>@media print{.rail,.topbar,.barre-mobile,.actions-h,footer,.mobile-share{display:none!important}.cadre,.colonne{display:block!important;width:100%!important;margin:0!important}main{padding:0!important}.carte{box-shadow:none!important}h2{break-after:avoid}}</style>`,user);
}
function validate(data){
 const p={};for(const [k,,type] of FIELDS){p[k]=type==='number'?( ['seuilPFF','absenceMax','stageSemaines'].includes(k)&&String(data[k]??'').trim()==='' ? '' : Number(data[k]||0)):String(data[k]||'').trim();if(type==='number'&&p[k]!==''&&(!Number.isFinite(p[k])||p[k]<0||!Number.isInteger(p[k])||p[k]>100000))throw Error('Valeur numérique invalide : '+k);if(type!=='number'&&p[k].length>12000)throw Error('Texte trop long : '+k);}
 if(!p.titre||!p.diplome||p.dureeAnnees<1||p.semestres<1)throw Error('Renseignez le titre, le diplôme, la durée et le nombre de semestres.');
 for(const k of ['poidsControle','poidsProjets','poidsStage','poidsComplementaire','seuilComposante','seuilPFF','absenceMax'])if(p[k]>100)throw Error('Les pourcentages et seuils doivent être compris entre 0 et 100.');
 if(p.poidsControle+p.poidsProjets+p.poidsStage+p.poidsComplementaire!==100)throw Error('Les pondérations d’évaluation doivent totaliser 100 %.');
 try{p.modules=JSON.parse(data.modules||'[]');}catch{throw Error('Liste de modules invalide.');}if(!Array.isArray(p.modules)||p.modules.length>200)throw Error('Maximum 200 modules.');
 p.modules=p.modules.map(m=>{if(!m||typeof m!=='object')throw Error('Module invalide.');const out={};for(const k of ['code','titre','contenu','objectifs','prerequis','evaluation','notesHoraires'])out[k]=String(m[k]||'').trim().slice(0,12000);for(const k of ['annee','semestre','theorie','pratique','stage','credits']){out[k]=Number(m[k]||0);if(!Number.isInteger(out[k])||out[k]<0||out[k]>100000)throw Error('Heures ou numérotation invalides pour '+out.titre);}if(!out.titre||out.annee<1||out.annee>p.dureeAnnees||out.semestre<1||out.semestre>p.semestres)throw Error('Chaque module nécessite un titre, une année et un semestre valides.');return out;});
 p.statut=data.statut==='publie'?'publie':'brouillon';p.confirmerHeures=data.confirmerHeures==='oui';
 if(p.statut==='publie'&&(!p.modules.length||!p.presentation||!p.objectifs||!p.admission||!p.conditionsDiplome))throw Error('Avant publication, complétez les modules, la présentation, les objectifs, les admissions et les conditions du diplôme.');
 if(p.statut==='publie'&&total(p)!==p.heuresAnnoncees&&!p.confirmerHeures)throw Error('Vérifiez et confirmez la différence de volume horaire avant publication.');return p;
}
async function handle(req,res,user){
 const path=req.pathname,method=req.method,db=DB.get();
 if(path==='/assets/programmes.js'&&method==='GET'){res.setHeader('Content-Type','application/javascript');res.end(require('fs').readFileSync(require('path').join(__dirname,'../assets/programmes.js')));return true;}
 if(!path.startsWith('/formateur/programmes')&&!path.startsWith('/programmes')&&!/^\/formateur\/formation\/crs_[a-z0-9]+\/programme$/.test(path))return false;
 db.programmes=db.programmes||[];
 const send=(s,h)=>{U.sendHTML(res,s,h);return true;};const redirect=u=>{U.redirect(res,u);return true;};
 if(path==='/programmes'&&method==='GET')return send(200,html('Programmes longs et diplômes techniques',`<p class="sous">Des parcours organisés en années, semestres, modules, stages et projets de fin de formation.</p>${canWrite(user)?'<a class="btn" href="/formateur/programmes">Gérer mes programmes</a>':''}<div class="grille g3" style="margin-top:20px">${db.programmes.filter(p=>p.statut==='publie').map(p=>`<article class="carte"><span class="badge b-bleu">${esc(p.grade)}</span><h2>${esc(p.titre)}</h2><p>${esc(p.presentation.slice(0,250))}</p><p>${p.dureeAnnees} ans · ${p.semestres} semestres · ${p.heuresAnnoncees} h</p><p>${esc(p.diplome)}</p><a class="btn" href="/programmes/${p.id}">Voir le programme complet</a></article>`).join('')||'<p>Aucun programme publié pour le moment.</p>'}</div>`,user));
 let sourceMatch=path.match(/^\/programmes\/(prg_[a-f0-9]+)\/source$/);
 if(sourceMatch&&method==='GET'){
  const p=db.programmes.find(p=>p.id===sourceMatch[1]);
  if(!p||p.statut!=='publie'&&!access(user,p)||!p.source)return send(404,html('Document introuvable','',user));
  const allowed=[MODEL.source,...require('../lib/programmes-importes.json').map(p=>p.source)];
  if(!allowed.includes(p.source))return send(404,html('Document introuvable','',user));
  const file=require('path').join(__dirname,'../docs',p.source);
  if(!require('fs').existsSync(file))return send(404,html('Document introuvable','',user));
  res.setHeader('Content-Type','application/pdf');res.setHeader('Cache-Control','no-store');require('fs').createReadStream(file).pipe(res);return true;
 }
 let m=path.match(/^\/programmes\/(prg_[a-f0-9]+)$/);
 if(m&&method==='GET'){const p=db.programmes.find(p=>p.id===m[1]);if(!p||p.statut!=='publie'&&!access(user,p))return send(404,html('Programme introuvable','',user));return send(200,details(p,user));}
 if(!user)return redirect('/login?suite='+encodeURIComponent(path));
 if(!canWrite(user))return send(403,html('Accès réservé','<p>La création de programmes est réservée aux formateurs approuvés et aux administrateurs.</p>',user));
 if(path==='/formateur/programmes'&&method==='GET')return send(200,html('Mes programmes longs',`<div class="actions-h"><a class="btn" href="/formateur/programmes/nouveau">Créer un programme</a><a class="btn ligne" href="/formateur/programmes/nouveau?modele=bureautique">Utiliser le modèle Bureautique EDUCA</a><a class="btn ligne" href="/formateur">Mon espace formations</a></div><div class="grille g3" style="margin-top:20px"><p class="panneau">Les programmes EDUCA importés sont disponibles ci-dessous en brouillons. Ouvrez Configurer pour les vérifier et les publier.</p>${db.programmes.filter(p=>access(user,p)).map(p=>`<article class="carte"><h2>${esc(p.titre)}</h2><p>${esc(p.diplome)} · ${p.dureeAnnees} ans</p><span class="badge b-bleu">${p.statut==='publie'?'Publié':'Brouillon'}</span><p><a class="btn" href="/formateur/programmes/${p.id}">Configurer</a> <a href="/programmes/${p.id}">Aperçu</a></p></article>`).join('')||'<p>Créez un programme vide ou partez du modèle détaillé.</p>'}</div>`,user));
 m=path.match(/^\/formateur\/formation\/(crs_[a-z0-9]+)\/programme$/);
 if(m&&method==='POST'){const c=db.courses.find(c=>c.id===m[1]);if(!c||c.formateurId!==user.id&&user.role!=='admin')return send(403,html('Accès refusé','',user));const {data}=await U.readBody(req, 4 * 1024 * 1024);if(data.csrf!==csrf(user))return send(403,html('Session invalide','Rechargez la page.',user));const p=db.programmes.find(p=>p.id===data.programmeId&&access(user,p));if(data.programmeId&&!p)return send(400,html('Programme invalide','',user));c.programmeId=p?p.id:null;DB.save();return redirect('/formateur/formation/'+c.id);}
 m=path.match(/^\/formateur\/programmes\/(nouveau|prg_[a-f0-9]+)$/);
 if(m){let p=m[1]==='nouveau'?null:db.programmes.find(p=>p.id===m[1]);if(m[1]!=='nouveau'&&(!p||!access(user,p)))return send(404,html('Programme introuvable','',user));if(method==='GET'){if(!p)p=req.query.get('modele')==='bureautique'?{...structuredClone(MODEL),statut:'brouillon'}:{grade:'Diplôme technique',dureeAnnees:2,semestres:4,poidsControle:30,poidsProjets:40,poidsStage:30,seuilComposante:60,seuilPFF:65,absenceMax:20,modules:[]};return send(200,editor(p,user));}
 if(method==='POST'){const {data}=await U.readBody(req, 4 * 1024 * 1024);if(data.csrf!==csrf(user))return send(403,html('Session invalide','Rechargez le formulaire.',user));try{const next=validate(data);if(p)Object.assign(p,next,{updatedAt:new Date().toISOString()});else{p={...next,id:'prg_'+crypto.randomBytes(6).toString('hex'),ownerId:user.id,createdAt:new Date().toISOString()};db.programmes.push(p);}DB.save();return redirect('/programmes/'+p.id);}catch(e){let modules=[];try{modules=JSON.parse(data.modules||'[]');if(!Array.isArray(modules))modules=[];}catch{}return send(422,editor({...data,id:p?.id,modules},user,e.message));}}
 }
 return send(404,html('Page introuvable','',user));
}
function courseEditor(c,user){const db=DB.get();db.programmes=db.programmes||[];return `<section class="carte" style="margin:18px 0"><h2>Programme long et diplôme technique</h2><p>Associez cette formation à un programme pour enrichir sa présentation publique avec les objectifs, compétences, admission, stage et conditions du diplôme.</p><form method="POST" action="/formateur/formation/${c.id}/programme"><input type="hidden" name="csrf" value="${csrf(user)}"><label>Programme associé</label><select name="programmeId"><option value="">Formation indépendante</option>${db.programmes.filter(p=>access(user,p)).map(p=>`<option value="${p.id}" ${c.programmeId===p.id?'selected':''}>${esc(p.titre)} (${p.statut})</option>`).join('')}</select><button class="btn" style="margin-top:12px">Enregistrer l’association</button></form><p><a href="/formateur/programmes/nouveau?modele=bureautique">Créer un programme à partir du modèle Bureautique</a></p></section>`;}
function coursePublic(c,user){const p=(DB.get().programmes||[]).find(p=>p.id===c.programmeId&&(p.statut==='publie'||access(user,p)));if(!p)return '';return `<section class="carte" style="margin-top:18px"><span class="badge b-bleu">Programme long · ${esc(p.grade)}</span><h2>${esc(p.titre)}</h2><p>${esc(p.diplome)} · ${p.dureeAnnees} ans · ${p.semestres} semestres · ${p.heuresAnnoncees} h</p>${blocks(p.presentation)}<h3>Objectifs</h3>${blocks(p.objectifs)}<h3>Compétences à acquérir</h3>${blocks(p.competences)}<h3>Admission</h3>${blocks(p.admission)}<h3>Débouchés</h3>${blocks(p.debouches)}<h3>Diplôme délivré et conditions</h3>${blocks(p.conditionsDiplome)}<a class="btn" href="/programmes/${p.id}">Parcours, stage et évaluations : voir le programme complet</a></section>`;}
module.exports={handle,courseEditor,coursePublic,validate,total};
